name: Search Tweets and Save
on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/30 * * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install Dependencies
      run: curl -L "https://github.com/arash16/arash16.com/releases/download/tweetsync-1.1/sync.js" -o sync.js
    - name: Sync Tweets to current Branch
      env:
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
      run: node sync.js github.com
